# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-28 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170928_1203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Extra',
            new_name='Profile',
        ),
    ]
