# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-28 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170928_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
