# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-07 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_twitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='twitter',
        ),
    ]
