# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-09 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_twitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='prefix',
        ),
    ]
