# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-10 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20171109_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriberemail',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
