# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-10 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20171109_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberemail',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
