# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0012_auto_20170517_1023'),
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='action',
            managers=[
                ('tweets', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='congress.Congress'),
        ),
        migrations.AlterField(
            model_name='action',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_model', to='programs.Program'),
        ),
    ]
