# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0013_auto_20170517_1558'),
        ('actions', '0002_auto_20170517_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='receiver',
        ),
        migrations.AddField(
            model_name='action',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='congress.Congress'),
        ),
    ]
