# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_auto_20170517_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='programs.Program'),
        ),
    ]
