# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from congress.models import Congress
# this check is needed for initial migrations on new environments
try:
    congress_id = Congress.objects.first().id
except:
    congress_id = 0

class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='congress',
            field=models.ForeignKey(default=congress_id, on_delete=django.db.models.deletion.CASCADE, to='congress.Congress'),
            preserve_default=False,
        ),
    ]
