# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0007_auto_20170526_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='fields',
            field=models.TextField(null=True),
        ),
    ]
