# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-28 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0008_email_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='fields',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
