# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0009_auto_20170828_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='programs.Program'),
        ),
    ]
