# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-18 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0013_email_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
