# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-29 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0014_email_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='action',
            managers=[
            ],
        ),
    ]
