# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-28 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_auto_20171026_1216'),
        ('hashtag', '0002_auto_20171018_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtagcounter',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.Campaign'),
        ),
    ]
