# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-14 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0003_auto_20170414_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congress',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='lis_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
