# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-14 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0004_auto_20170414_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congress',
            name='leadership_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='name_suffix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='state_rank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
