# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-14 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0005_auto_20170414_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congress',
            name='bioguide_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='chamber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='contact_form',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='crp_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='fec_ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='gender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='ocd_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='party',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='senate_class',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='term_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='term_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='thomas_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='votesmart_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
