# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-14 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0006_auto_20170414_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congress',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='govtrack_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='oc_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='twitter_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
