# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-14 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0007_auto_20170414_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congress',
            name='bioguide_id',
            field=models.CharField(default=123, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='congress',
            name='twitter_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
