# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0008_auto_20170414_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congress',
            name='image',
        ),
    ]
