# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 23:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0010_auto_20170424_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congress',
            name='zip',
        ),
        migrations.AddField(
            model_name='congress',
            name='zips',
            field=models.CharField(blank=True, max_length=1000, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.DeleteModel(
            name='Zip',
        ),
    ]
