# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0015_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='congress',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='congress.Congress'),
        ),
    ]
