# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0016_auto_20170526_0603'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fields',
            new_name='Field',
        ),
    ]
