# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0019_emailfield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailField',
            new_name='APIEmailField',
        ),
    ]
