# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 23:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0020_auto_20170527_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiemailfield',
            old_name='fields',
            new_name='email_fields',
        ),
    ]
