# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0021_auto_20170527_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congresscounter',
            name='program',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='programs.Program'),
        ),
    ]
