# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0022_auto_20170906_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congresscounter',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.Program'),
        ),
    ]
