# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-07 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0023_auto_20170906_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congress',
            options={},
        ),
        migrations.AddField(
            model_name='congress',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
