# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-07 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0024_auto_20170906_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congress',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
        migrations.RemoveField(
            model_name='congress',
            name='counter',
        ),
    ]
