# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-07 06:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0026_congresscounter_campaign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='congress',
            old_name='facebook_id',
            new_name='facebook',
        ),
        migrations.AddField(
            model_name='congress',
            name='ballotpedia_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='congress',
            name='cspan_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='congress',
            name='google_entity_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='congress',
            name='icpsr_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='congress',
            name='maplight_id',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='congress',
            name='rss_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='congress',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='congress',
            name='wikipedia_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='fec_ids',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='congress',
            name='zips',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
