# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-07 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0027_auto_20171007_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='congress',
            name='instagram',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='congress',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='congress',
            name='twitter',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='congress',
            name='youtube',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='congress',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
