# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-07 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0028_auto_20171007_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congress',
            name='maplight_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
