# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-07 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0029_auto_20171007_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='congress',
            name='full_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
