# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-07 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0030_congress_full_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='congress',
            name='opensecrets_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
