# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-07 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0032_congress_office_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congress',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='congress',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
