# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0035_auto_20171007_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congress',
            name='fec_ids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
