# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0002_auto_20160217_1722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet2',
            new_name='SegmentAPI',
        ),
    ]
