# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-14 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
