# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20170414_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='actions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='program',
            name='users',
            field=models.IntegerField(default=0),
        ),
    ]
