# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20170415_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='description',
            new_name='plot_outline',
        ),
    ]
