# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 00:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_program_imdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='imdb',
            new_name='imdb_id',
        ),
    ]
