# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_auto_20170418_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
