# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_auto_20170418_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='plot_outline',
            new_name='description',
        ),
    ]
