# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_auto_20170511_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='description',
            new_name='plot_outline',
        ),
    ]
