# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_auto_20170511_1002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={},
        ),
        migrations.RenameField(
            model_name='program',
            old_name='actions',
            new_name='counter',
        ),
    ]
