# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0013_auto_20170517_1558'),
        ('programs', '0010_auto_20170517_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='CongressCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('counter', models.IntegerField(default=0)),
                ('congress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congress.Congress')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='congresscounter',
            unique_together=set([('congress', 'program')]),
        ),
    ]
