# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_auto_20170517_1558'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='congresscounter',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='congresscounter',
            name='congress',
        ),
        migrations.RemoveField(
            model_name='congresscounter',
            name='program',
        ),
        migrations.DeleteModel(
            name='CongressCounter',
        ),
    ]
