# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0012_auto_20170517_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
