# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-15 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_program_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='season',
        ),
        migrations.RemoveField(
            model_name='season',
            name='program',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='program',
        ),
        migrations.AddField(
            model_name='program',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.DeleteModel(
            name='Segment',
        ),
    ]
