# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-15 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0014_auto_20170815_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
