# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-13 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0016_auto_20170816_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='url',
        ),
    ]
