# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-31 13:02
from __future__ import unicode_literals

from imdbpie import Imdb

from django.db import migrations


def mark_imdb_programs_as_documentaries(apps, schema_editor):
    Program = apps.get_model('programs', 'Program')
    Program.objects.exclude(imdb_id="").update(type='documentary')


def mark_imdb_programs_as_their_type_on_imdb(apps, schema_editor):
    imdb = Imdb(anonymize=True)
    Program = apps.get_model('programs', 'Program')
    for program in Program.objects.filter(type='documentary').exclude(
            imdb_id__isnull=True).exclude(imdb_id=""):
        data = imdb.get_title_by_id(program.imdb_id)
        program.type = data.type
        program.save(update_fields=['type'])


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0017_remove_program_url'),
    ]

    operations = [
        migrations.RunPython(mark_imdb_programs_as_documentaries,
                             mark_imdb_programs_as_their_type_on_imdb),
    ]
