# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-20 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='email_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='tweet_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
