# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_campaign_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={},
        ),
        migrations.AddField(
            model_name='campaign',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
