# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_auto_20170926_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='link',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
    ]
